### ISSUE TITLE
Sample compile error

### ISSUE THREAD

**Issue by LiuOcean** [bustedbunny/com.bustedbunny.mvvmtoolkit#3]
The [ItemColletionBinder](https://github.com/bustedbunny/com.bustedbunny.mvvmtoolkit/blob/110b2cacb90e43f382b48f51290dfd5e74ff53d3/Runtime/Binding/CollectionBinding/Generics/ItemCollectionBinder.cs#L5) has been  removed, yet it is still being used in the [CollectionViewViewModel](https://github.com/bustedbunny/com.bustedbunny.mvvmtoolkit/blob/d7c64050bf1dcc18cc20807c52d9de5a26fa2e21/Samples~/SampleView/Views/CollectionView/CollectionViewViewModel.cs#L62). While it worked fine in version 1.0.0-pre.12 sample, it now causes the following compilation errors in version 1.0.0-pre.16 sample.

```
Assets/Samples/Model-View-ViewModel Toolkit/1.0.0-pre.16/Sample View/Views/CollectionView/CollectionViewViewModel.cs(71,41): error CS0246: The type or namespace name 'ItemCollectionBinder<,>' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by Bian-Sh** [comment]
me too...

**Comment by Bian-Sh** [comment]
在上一次提交时，作者删除了关于 集合 的逻辑，只需要把报错的地方尽情删除即可
In the previous submission, the author omitted the logic related to "collections," simply delete the parts that are causing errors.
